server {
    listen 80;

    location /layout/ {
        proxy_pass         http://layout:80/layout/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /host-a/ {
        proxy_pass         http://host-a:80/host-a/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /host-b/ {
        proxy_pass         http://host-b:80/host-b/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location = / {
        return 302 /host-a/;
    }
}
